#!/usr/bin/python3.1
# -*- coding:utf-8 -*-
#
# hotspot-login-manager
# https://github.com/syam44/Hotspot-Login-Manager
#
# Distributed under the GNU General Public License version 3
# https://www.gnu.org/copyleft/gpl.html
#
# Authors: syam (aks92@free.fr)
#
# Description: Entry point.
#
# Note: Keeping the main script to the bare minimum enhances load-time
#       thanks to precompiled .pyc files.
#       So yeah, *bare* minimum.
#


#-----------------------------------------------------------------------------
import sys # This must be imported first to ensure sys.exit() works
try:
    # Do not import any HLM module before this one, translation services are needed everywhere!
    import hotspot_login_manager.libs.core.hlm_i18n
    #
    from hotspot_login_manager.libs import hlm_main

except ImportError as err:
    # No i18n here since we have no guarantee that the translation services are correctly installed.
    print('Couldn\'t load module: {0}.'.format(err))
    sys.exit(255)


#-----------------------------------------------------------------------------
if __name__ == '__main__':
   hlm_main.main()


#-----------------------------------------------------------------------------
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4
