#!/usr/bin/python2.7
# -*- coding:utf-8 -*-
#
# hotspot-login-manager
# https://github.com/syam44/Hotspot-Login-Manager
#
# Distributed under the GNU General Public License version 3
# https://www.gnu.org/copyleft/gpl.html
#
# Authors: syam (aks92@free.fr)
#
# Description: Entry point.
#


#-----------------------------------------------------------------------------
try:
    import sys
    #
    from hotspot_login_manager.libs import hlm_network
    #
    import hotspot_login_manager.libs.hlm_i18n
    _, _N = hotspot_login_manager.libs.hlm_i18n.translators()

except ImportError as err:
    print('Couldn\'t load module. {0}.'.format(err))
    sys.exit(255)


#-----------------------------------------------------------------------------
def main():
    hotspot_login_manager.libs.hlm_i18n.init(__file__)

    print _(u'All interfaces'), hlm_network.getInterfaces(wifiOnly = False)
    wirelessIfaces = hlm_network.getInterfaces(wifiOnly = True)
    print _N(u'Wireless interface', u'Wireless interfaces', len(wirelessIfaces)), wirelessIfaces
    for iface in wirelessIfaces:
        print '    ', iface, '=', hlm_network.getSSID(iface)

    sys.exit(0)


#-----------------------------------------------------------------------------
if __name__ == '__main__':
   main()


#-----------------------------------------------------------------------------
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4
