#!/usr/bin/python3.1
# -*- coding:utf-8 -*-
#
# hotspot-login-manager
# https://github.com/syam44/Hotspot-Login-Manager
#
# Distributed under the GNU General Public License version 3
# https://www.gnu.org/copyleft/gpl.html
#
# Authors: syam (aks92@free.fr)
#
# Description: Entry point.
#


#-----------------------------------------------------------------------------
try:
    import hotspot_login_manager.libs.hlm_i18n
    #
    import sys
    #
    from hotspot_login_manager.libs import hlm_args

except ImportError as err:
    print('Couldn\'t load module: {0}.'.format(err))
    sys.exit(255)


#-----------------------------------------------------------------------------
def main():
    args = hlm_args.parse()

    #
    # Sample code below
    #

    # --daemon
    if args.runDaemon:
        from hotspot_login_manager.libs import hlm_wifi
        #
        print(_('All interfaces'), hlm_wifi.getNetworkInterfaces(wifiOnly = False))
        wirelessIfaces = hlm_wifi.getNetworkInterfaces(wifiOnly = True)
        print(_N('Wireless interface', 'Wireless interfaces', len(wirelessIfaces)), wirelessIfaces)
        for iface in wirelessIfaces:
            print('    ', iface, '=', hlm_network.getSSID(iface))

    # --notifier=kde4
    elif args.notifierBackend != None:
        import subprocess
        import time
        from hotspot_login_manager.libs import hlm_defaultpaths
        #
        iteration = 0
        while True:
            iteration += 1
            message = _('Notification #{0}\nIt works!').format(iteration)
            subprocess.Popen([hlm_defaultpaths.application() + '/hotspot_login_manager/notifiers/' + args.notifierBackend, message])
            time.sleep(5)

    sys.exit(0)


#-----------------------------------------------------------------------------
if __name__ == '__main__':
   main()


#-----------------------------------------------------------------------------
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4
