#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")/../hotspot_login_manager/lang"

for POFILE in *.po; do
  POLANG="$(echo "$POFILE" | sed 's@\.po$@@g')"
  PODIR="$POLANG/LC_MESSAGES"
  mkdir -p "$PODIR"
  msgfmt --strict "$POFILE"
  mv messages.mo "$PODIR/hotspot-login-manager.mo"
done
