#!/bin/sh
#
# hotspot-login-manager
# https://github.com/syam44/Hotspot-Login-Manager
#
# Distributed under the GNU General Public License version 3
# https://www.gnu.org/copyleft/gpl.html
#
# Authors: syam (aks92@free.fr)
#
# Description: Install the various hooks and configuration files required for HLM
#
set -e

cd "$(dirname "$(readlink -f "$0")")/.."

installFile()
{
    local RIGHTS="$1"
    local FILE="$2"
    if [ ! -e "$FILE" ]; then
        cp "distrib/$FILE" "$FILE"
        chown root:root "$FILE"
        chmod "$RIGHTS" "$FILE"
    fi
}
removeFile()
{
    local FILE="$1"
    if [ -e "$FILE" ]; then
        rm "$FILE" || true
    fi
}

case "$1" in
  install)
        "$0" remove
        installFile a-ws,a+rx,u+w "/etc/init.d/hotspot-login-manager"
        installFile a-ws,a+rx,u+w "/etc/network/if-up.d/hotspot-login-manager"
        ln -s "/etc/network/if-up.d/hotspot-login-manager" "/etc/network/if-down.d/hotspot-login-manager"
        mkdir -p "/etc/hotspot-login-manager"
        chmod a-rwxs,u+rwx "/etc/hotspot-login-manager"
        installFile a-rwxs,u+rw "/etc/hotspot-login-manager/daemon.conf"
        installFile a-rwxs,u+rw "/etc/hotspot-login-manager/credentials.conf"
        ln -s "$(readlink -f ./hotspot-login-manager.py)" /usr/local/bin/hotspot-login-manager
        # FIXME: update-rc.d hotspot-login-manager defaults
        # FIXME: /etc/init.d/hotspot-login-manager start
        ;;
  uninstall)
        if [ -x /etc/init.d/hotspot-login-manager ]; then
          /etc/init.d/hotspot-login-manager stop || true
        fi
        update-rc.d hotspot-login-manager remove || true
        removeFile "/etc/init.d/hotspot-login-manager"
        removeFile "/etc/network/if-up.d/hotspot-login-manager"
        removeFile "/etc/network/if-down.d/hotspot-login-manager"
        removeFile "/usr/local/bin/hotspot-login-manager"
        ;;
  purge)
        "$0" remove
        removeFile "/etc/hotspot-login-manager/daemon.conf"
        removeFile "/etc/hotspot-login-manager/credentials.conf"
        [ -e "/etc/hotspot-login-manager" ] && { rmdir "/etc/hotspot-login-manager" || true; }
        ;;
esac
