#!/bin/sh
#
# hotspot-login-manager
# https://github.com/syam44/Hotspot-Login-Manager
#
# Distributed under the GNU General Public License version 3
# https://www.gnu.org/copyleft/gpl.html
#
# Authors: syam (aks92@free.fr)
#
# Description: I18N: Generate messages.pot translation model
#
set -e

MESSAGES_POT="$1"
shift
PY_FILES="$@"

# .pot header
cat >"$MESSAGES_POT.tmp" <<EOF
#
# hotspot-login-manager
# https://github.com/syam44/Hotspot-Login-Manager
#
# Distributed under the GNU General Public License version 3
# https://www.gnu.org/copyleft/gpl.html
#
msgid ""
msgstr ""
"Project-Id-Version: hotspot-login-manager $(cat ./VERSION)\n"
"POT-Creation-Date: $(date --utc +'%Y-%m-%d %H:%M+%Z')\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: UTF-8\n"
"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n"
"Generated-By: hotspot-login-manager/devtools/make-i18n-pot\n"
EOF

# Extract strings, remove default header (we already have one), and append to existing header
./devtools/pygettext/pygettext3 --output=- $PY_FILES | tail -n +17 >>"$MESSAGES_POT.tmp"

# Do not replace the .pot file if there are no changes (avoids bumping the POT-Creation-Date field, which helps versioning)
filter_pot()
{
    cat "$1" 2>/dev/null | sed 's@^"POT-Creation-Date: [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [0-9]\{2\}:[0-9]\{2\}+[A-Z]\+\\n"$@"POT-Creation-Date: YEAR-MO-DA HO:MI+ZONE\n"@g'
}
CURRENT_POT="$(filter_pot "$MESSAGES_POT")"
NEW_POT="$(filter_pot "$MESSAGES_POT.tmp")"

if [ "$CURRENT_POT" = "$NEW_POT" ]; then
    echo "No changes to .pot file."
    rm "$MESSAGES_POT.tmp"
    touch "$MESSAGES_POT"
else
    mv "$MESSAGES_POT.tmp" "$MESSAGES_POT"
fi
