#!/bin/sh

#
# hotspot-login-manager
# https://github.com/syam44/Hotspot-Login-Manager
#
# Distributed under the GNU General Public License version 3
# https://www.gnu.org/copyleft/gpl.html
#
# Authors: syam (aks92@free.fr)
#
# Description: Automatic daemon reauthentification whenever an interface goes up or down.
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Gracefully exit if the package has been removed.
test -x "$(which hotspot-login-manager)" || exit 0

hotspot-login-manager --reauth

exit 0
