#!/bin/sh
# -*- coding:utf-8 -*-
#
# hotspot-login-manager
# https://github.com/syam44/Hotspot-Login-Manager
#
# Distributed under the GNU General Public License version 3
# https://www.gnu.org/copyleft/gpl.html
#
# Authors: syam (aks92@free.fr)
#
# Description: Notification command for unpriviledged users.
#              This is the KDE4 version, using kdialog under the hood.
#


#
# "$1" is the notification message.
#
kdialog --passivepopup "$1" 5 --title "Hotspot Login Manager"
