#!/bin/sh
# -*- coding:utf-8 -*-
#
# hotspot-login-manager
# https://github.com/syam44/Hotspot-Login-Manager
#
# Distributed under the GNU General Public License version 3
# https://www.gnu.org/copyleft/gpl.html
#
# Authors: syam (aks92@free.fr)
#
# Description: Notification command for unpriviledged users.
#              This is the KDE4 version, using kdialog under the hood.
#
#              If you happen to use a notification system that is not
#              already provided by HLM, please notify us (if you can write
#              the code it's even better, since testing on an unknown
#              environment may be quite hard for us).
#


#
# "$1" is the notification message.
#
kdialog --passivepopup "$1" 5 --title "Hotspot Login Manager"
