#!/bin/sh
# -*- coding:utf-8 -*-
#
# hotspot-login-manager
# https://github.com/syam44/Hotspot-Login-Manager
#
# Distributed under the GNU General Public License version 3
# https://www.gnu.org/copyleft/gpl.html
#
# Authors: syam (aks92@free.fr)
#
# Description: Notification command for unpriviledged users.
#              This is the KDE4 version, using kdialog under the hood.
#

if [ "$1" = "" ]; then
  # Check if we are running on KDE4
  [ -x "$(which kdialog)" ] && [ "$KDE_FULL_SESSION" = "true" ] && [ "$KDE_SESSION_VERSION" = "4" ] && exit 0
  exit 1
else
  # Show the notification
  kdialog --passivepopup "$1" 5 --title "Hotspot Login Manager"
fi
