# -*- coding:utf-8 -*-
#
# hotspot-login-manager
# https://github.com/syam44/Hotspot-Login-Manager
#
# Distributed under the GNU General Public License version 3
# https://www.gnu.org/copyleft/gpl.html
#
# Authors: syam (aks92@free.fr)
#
# Description: Current version of the project.
#
#              THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY "make version", DO NOT MODIFY IT!
#
#              If you want to change the version, modify the root "VERSION" file
#              and run "make version" again.
#


#-----------------------------------------------------------------------------
def getVersion():
    return '0.0~devel'


#-----------------------------------------------------------------------------
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4
